# Generated by Django 5.2 on 2025-08-12 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prodcut',
            new_name='product',
        ),
    ]
